### ISSUE TITLE
Android - Tap on notification doesn't open the app 

### ISSUE THREAD

**Issue by an83** [edsnider/Xamarin.Plugins#10]
Hi, I run your sample code on Android. The notification appeared as expected, but when I click on the notification it doesn't open the app. 

I think it's bceause .SetContentIntent (pendingIntent) is not implemented  
https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/local_notifications_in_android/

Also the icon on the notification is blank on nuget package version 1.0.2

**Comment by jamesmontemagno** [comment]
Please check 2.0.1, just implemented it. Now have a default icon and also allow you to override.
