### ISSUE TITLE
Keep notifications after boot

### ISSUE THREAD

**Issue by jerone** [edsnider/Xamarin.Plugins#11]
I would like to set some notifications that are even kept after a boot of the device. For iOS they [seem to be kept](http://stackoverflow.com/questions/8573013/uilocalnotification-when-iphone-switched-off), but for Android this doesn't seem to work. Not sure about Windows Phone.

Ref: http://stackoverflow.com/questions/27490329/is-there-an-equivalent-solution-like-ioss-localnotification-on-android-platform

**Comment by jerone** [comment]
I actually already solved this in my app by serializing all timed notifications by id and store them in the shared settings. Then I register a boot receiver that reads the shared settings again and check for not already triggered notifications to restart the alarm manager.

**Comment by jamesmontemagno** [comment]
Is this just for notifications that were currently being displayed? Or is this for scheduled notifications? I would be interested in a pull re-request if it was the latter as that could be useful.

**Comment by jerone** [comment]
I meant for scheduled notifications only.

**Comment by jamesmontemagno** [comment]
Interesting, so currently if you schedule a notification for tomorrow and the user reboots the device then the message is lost? If this is the case, I would be interested in incorporating your code into the project as I think it should retain them. Could use my Settings Plugin to handle it: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Settings

**Comment by jerone** [comment]
> Interesting, so currently if you schedule a notification for tomorrow and the user reboots the device then the message is lost?

Yes this happened on a few devices at our end.

The app where I implemented this for isn't open source, so I can't share the code. Besides I altered it a lot to suit our needs. My comment above summarized the big parts of it. 

> Could use my Settings Plugin to handle it

You could use your Settings Plugin for it, but saving notifications is only needed for Android, as both iOS and Windows Phone show the notifications after reboot.

**Comment by jamesmontemagno** [comment]
Gotcha, I should be able to get it going from here and will test it out. When it is ready I will ping and maybe you can do a code review from a branch I create.

**Comment by De4th69** [comment]
Hey James. Is there currently a schedule when you can add this?

**Comment by Femilshajin** [comment]
Is there a way to schedule it repeatedly every day??

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
