### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by agoodmiller** [edsnider/Xamarin.Plugins#12]
When i try to add the package through Xamarin i get the following error : 

Could not install package 'Xam.Plugins.Notifier 1.0.2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any idea on how to get around that?

**Comment by jamesmontemagno** [comment]
Please test out 2.0.0.  It should be fine to install. are you in Xamarin Studio or visual studio?

**Comment by agoodmiller** [comment]
I am using Xamarin Studio on the mac.

**Comment by jamesmontemagno** [comment]
Just test it and it is working great. I have Version 5.10 (build 871) of Xamarin Studio.

**Comment by agoodmiller** [comment]
Ok. Great!

I'll give it a shot tomorrow. 



-- Aaron

On Dec 1, 2015, at 4:05 PM, James Montemagno <notifications@github.com> wrote:

Closed #12.
