### ISSUE TITLE
Notification Icon Change and Navigation

### ISSUE THREAD

**Issue by KathirveluM** [edsnider/Xamarin.Plugins#18]
Hi Team,
We are using the Xamarin.Plugins for showing notifications in Xamarin Forms application.  We need to achieve the below in our scenario. 

1. How to Change Notification Icon from Core Project.
2. we need to navigate to particular screen while clicking on the Notification .

Kindly suggest on this.

**Comment by jamesmontemagno** [comment]
1.) You can do this on android by seeing: https://github.com/edsnider/Xamarin.Plugins/blob/master/Notifier/Plugin.LocalNotifications.Android/LocalNotificationsImplementation.cs#L19

It only launches your mainlauncher of your application.

**Comment by KathirveluM** [comment]
James,
1. Then how about iOS platform ?
2. " We need to navigate to particular screen while clicking on the Notification " ?

**Comment by jamesmontemagno** [comment]
1.) It just uses your app icon at this moment, as I think that is all iOS supports, would have to look into it.
2.) Not supported at this time. 

If you need to advance the plugin you can always fork and send a pull request, or pull the code into your app to extend it further for your use case.

**Comment by KathirveluM** [comment]
Thanks for the information James. 
Will  the 2nd point will be implemented in future? if yes, approximately when the same will be implemented?

**Comment by KathirveluM** [comment]
Hi James,
Do you mentioning this " builder.SetSmallIcon(Resource.Drawable.**plugin_lc_smallicon**);" to change the required icon(ours) to show in android platform?

if not, where we need to  change exactly for android platform?

Thanks in Advance.

**Comment by KathirveluM** [comment]
Thanks for the information James.

Will the 2nd point will be implemented in future? if yes, approximately when the same will be implemented?

Is this will be released soon?
