### ISSUE TITLE
Is it possible to change the Icon displayed?

### ISSUE THREAD

**Issue by JKennedy24** [edsnider/Xamarin.Plugins#31]
Is it possible to change the Icon displayed on iOS / Android and UWP?

I would have thought it would have been useful for the Interface to have a method that takes a string "IconPath"

and tries to set the icon on each platform

**Comment by jamesmontemagno** [comment]
On ANdroid you can from your Android project.

Call and set: LocalNotificationsImplementation.NotificationIconId to your Resource.Drawable.icon
