### ISSUE TITLE
[Official Update]No longer supported

### ISSUE THREAD

**Issue by jamesmontemagno** [edsnider/Xamarin.Plugins#37]
This library has been officially discontinued and needs to be re-vamped for new OS changes.

**Comment by LukasThijs** [comment]
OK :) Is there any date set or nuget that I need to keep an eye on as a replacement ?

**Comment by edsnider** [comment]
I've updated the package to support the changes for iOS 10.  Just doing some final testing and then will update the existing NuGet package.

**Comment by LukasThijs** [comment]
Great take your time :)! Also quick reply if I may add.

While we are at it any update on the following:

Currently, if the phone is re-booted then the pending notifications are not sent, you should save them out to settings and re-send on re-boot.

I can't wrap my mind around how to even achieve this tips would be appreciated!

Thanks in advance,

Luuk

**Comment by LukasThijs** [comment]
Hey @edsnider,

Any status update on the support changes :)? The string Title in iOS returns null when a notification is shown. Will this update address this bug as well?


Thanks in advance,

luuk

**Comment by edsnider** [comment]
@LukasThijs hopefully this week :) 

The Title issue you mentioned... looks like we're assigning the title to the `AlertAction` property and it should probably be assigned to the `AlertTitle` property instead.  Will get that fixed for iOS 9 and back.

**Comment by LukasThijs** [comment]
Great ill keep an eye on the Nuget manager :)

**Comment by edsnider** [comment]
Plugin has been updated to support iOS 10's new UserNotifications framework.  NuGet package update is available (v.2.1.0) https://www.nuget.org/packages/Xam.Plugins.Notifier/

**Also**: This plugin has been moved to an independent repo at https://github.com/edsnider/LocalNotificationsPlugin

Be sure to checkout the notes in the README about requesting user permission and handling notifications when the app is active for iOS 10.

**Comment by LukasThijs** [comment]
Thanks it works like a charm :)!
