### ISSUE TITLE
Using the NuGet with Xamarin.iOS 8.10 throws an exception

### ISSUE THREAD

**Issue by mattleibow** [edsnider/Xamarin.Plugins#4]
This is the exception I get:

> Failed to resolve "Foundation.NSDate Foundation.NSDate::op_Implicit(System.DateTime)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

I rebuilt the repo and this fixes the issue. It must be related to some internal chnages

**Comment by edsnider** [comment]
Fixed in commit 0d684bbacb3cdac711406cde4f62c7494fb3a860 and included in NuGet package version 1.0.2.
