### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by philipag** [edsnider/Xamarin.Plugins#6]
Hi Ed. 

Nice Library!  I am looking at adding sound notifications and vibration as well (alerts).  Is this something you are already working on?  I'd be happy to contribute back and keep a single code base.

Cheers

**Comment by edsnider** [comment]
Hi!
I am not currently working on those features.  If you want to contribute, that would be awesome.  Feel free to issue a PR!
Thanks!
Ed

**Comment by philipag** [comment]
OK, thanks.
    
    Ed Snider wrote:
    
    
      Hi!
        I am not currently working on those features. If you want to
        contribute, that would be awesome. Feel free to issue a PR!
        Thanks!
        Ed
      —
        Reply to this email directly or view
          it on GitHub.
